# run: conda env create --file environment.yml
name: tensorflow-notebook
channels:
  - conda-forge
dependencies:
  - python >3.9,<3.11
  - pip
  - ipykernel
  - numpy >=1.17.3
  - scikit-learn >=1.1.0
  - matplotlib >= 3.1.2
  - pandas >=1.0.5
  - cudnn
  - pip:
      # works for regular pip packages
      - tensorflow >= 2.4.3
      - tensorflow-addons
      - tensorflow_datasets
      - tensorboard
      - wget
